// Code generated by protoc-gen-go. DO NOT EDIT.
// source: types.proto

/*
Package parse is a generated protocol buffer package.

It is generated from these files:
	types.proto

It has these top-level messages:
	TextMessage
	ChannelMessage
	PaymentResponse
	PaymentInvoice
*/
package parse

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Type int32

const (
	// Used as a wildcard for listeners to listen to all existing types.
	// Think of it as "No type in particular"
	Type_NO_TYPE Type = 0
	// See proto buf documentation below
	Type_TEXT_MESSAGE Type = 1
	// See proto buf
	Type_CHANNEL_MESSAGE Type = 2
	// Second field is the key data itself. This should be 2048 bits long
	// (according to the message length that our prime allows) and is
	// base64-encoded.
	Type_UDB_PUSH_KEY Type = 10
	// The push key response message is a string. If the key push was a
	// success, the UDB should respond with a message that starts with "PUSHKEY
	// COMPLETE", followed by the fingerprint of the key that was pushed.
	// If the response doesn't begin with "PUSHKEY COMPLETE", the message is
	// an error message and should be shown to the user.
	Type_UDB_PUSH_KEY_RESPONSE Type = 11
	// The get key message includes a single string field with the key
	// fingerprint of the key that needs gettin'. This is the same fingerprint
	// you would have pushed.
	Type_UDB_GET_KEY Type = 12
	// The get key response message is a string. The first space-separated
	// field should always be "GETKEY". The second field is the fingerprint of
	// the key. The third field is "NOTFOUND" if the UDB didn't find the key,
	// or the key itself, encoded in base64, otherwise.
	Type_UDB_GET_KEY_RESPONSE Type = 13
	// To wit: The first argument in the list of space-separated fields is
	// the type of the registration. Currently the only allowed type is
	// "EMAIL". The second argument is the value of the type you're registering
	// with. In all currently acceptable registration types, this would be an
	// email address. If you could register with your phone, it would be your
	// phone number, and so on. Then, the key fingerprint of the user's key is
	// the third argument. To register successfully, you must have already
	// pushed the key with that fingerprint.
	Type_UDB_REGISTER Type = 14
	// The registration response is just a string. It will be either an error
	// message to show to the user, or the message "REGISTRATION COMPLETE" if
	// registration was successful.
	Type_UDB_REGISTER_RESPONSE Type = 15
	// The search message is just another space separated list. The first field
	// will contain the type of registered user you're searching for, namely
	// "EMAIL". The second field with contain the value of that type that
	// you're searching for.
	Type_UDB_SEARCH Type = 16
	// The search response is a list of fields. The first is always "SEARCH".
	// The second is always the value that the user searched for. The third is
	// "FOUND" or "NOTFOUND" depending on whether the UDB found the user. If
	// the user was FOUND, the last field will contain their key fingerprint,
	// which you can use with GET_KEY to get the keys you need to talk with
	// that user. Otherwise, this fourth field won't exist.
	Type_UDB_SEARCH_RESPONSE Type = 17
	// To get a message of this type, call the methods in the wallet.
	// TODO expose these methods over the API
	Type_PAYMENT_TRANSACTION Type = 20
	// See proto buf
	Type_PAYMENT_RESPONSE Type = 21
	// See proto buf
	Type_PAYMENT_INVOICE Type = 22
	// This message type includes only the message hash of the original
	// invoice message. Since there are no fields to delimit, it's not a
	// proto buffer. When the payee gets a receipt back, they know that the
	// other person probably paid them, and to check the next published
	// blockchain for the images of their coins to make sure.
	Type_PAYMENT_RECEIPT Type = 23
	// This message type is a list of fixed-length hashes, currently 256 bits
	// each, that are used as indexes into the inbound requests transaction list
	Type_PAYMENT_INVOICE_UI Type = 9000
)

var Type_name = map[int32]string{
	0:    "NO_TYPE",
	1:    "TEXT_MESSAGE",
	2:    "CHANNEL_MESSAGE",
	10:   "UDB_PUSH_KEY",
	11:   "UDB_PUSH_KEY_RESPONSE",
	12:   "UDB_GET_KEY",
	13:   "UDB_GET_KEY_RESPONSE",
	14:   "UDB_REGISTER",
	15:   "UDB_REGISTER_RESPONSE",
	16:   "UDB_SEARCH",
	17:   "UDB_SEARCH_RESPONSE",
	20:   "PAYMENT_TRANSACTION",
	21:   "PAYMENT_RESPONSE",
	22:   "PAYMENT_INVOICE",
	23:   "PAYMENT_RECEIPT",
	9000: "PAYMENT_INVOICE_UI",
}
var Type_value = map[string]int32{
	"NO_TYPE":               0,
	"TEXT_MESSAGE":          1,
	"CHANNEL_MESSAGE":       2,
	"UDB_PUSH_KEY":          10,
	"UDB_PUSH_KEY_RESPONSE": 11,
	"UDB_GET_KEY":           12,
	"UDB_GET_KEY_RESPONSE":  13,
	"UDB_REGISTER":          14,
	"UDB_REGISTER_RESPONSE": 15,
	"UDB_SEARCH":            16,
	"UDB_SEARCH_RESPONSE":   17,
	"PAYMENT_TRANSACTION":   20,
	"PAYMENT_RESPONSE":      21,
	"PAYMENT_INVOICE":       22,
	"PAYMENT_RECEIPT":       23,
	"PAYMENT_INVOICE_UI":    9000,
}

func (x Type) String() string {
	return proto.EnumName(Type_name, int32(x))
}
func (Type) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

// Is Type.TEXT_MESSAGE
// Used for conveying simple text messages between users
type TextMessage struct {
	// Terminal text foreground color. Used by the console UI
	Color int32 `protobuf:"zigzag32,2,opt,name=color" json:"color,omitempty"`
	// The message text itself. Varies in length
	Message string `protobuf:"bytes,3,opt,name=message" json:"message,omitempty"`
	// Timestamp (Unix time in seconds)
	// You can use this to display the time when the other user sent the message
	// TODO Remove this when all messages have timestamps
	Time int64 `protobuf:"varint,4,opt,name=time" json:"time,omitempty"`
}

func (m *TextMessage) Reset()                    { *m = TextMessage{} }
func (m *TextMessage) String() string            { return proto.CompactTextString(m) }
func (*TextMessage) ProtoMessage()               {}
func (*TextMessage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *TextMessage) GetColor() int32 {
	if m != nil {
		return m.Color
	}
	return 0
}

func (m *TextMessage) GetMessage() string {
	if m != nil {
		return m.Message
	}
	return ""
}

func (m *TextMessage) GetTime() int64 {
	if m != nil {
		return m.Time
	}
	return 0
}

// Is Type.CHANNEL_MESSAGE
// This is the type of all messages that come from the channelbot.
type ChannelMessage struct {
	// This is the original speaker of the channel message, who sent the
	// message to the channel bot.
	SpeakerID []byte `protobuf:"bytes,3,opt,name=speakerID,proto3" json:"speakerID,omitempty"`
	// This is a serialized parse message under the hood. When writing a
	// listener for a channel message on a client, you need to unpack the
	// serialized parse message and rebroadcast it through the listeners.
	Message []byte `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
}

func (m *ChannelMessage) Reset()                    { *m = ChannelMessage{} }
func (m *ChannelMessage) String() string            { return proto.CompactTextString(m) }
func (*ChannelMessage) ProtoMessage()               {}
func (*ChannelMessage) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *ChannelMessage) GetSpeakerID() []byte {
	if m != nil {
		return m.SpeakerID
	}
	return nil
}

func (m *ChannelMessage) GetMessage() []byte {
	if m != nil {
		return m.Message
	}
	return nil
}

// Is Type.PAYMENT_RESPONSE
type PaymentResponse struct {
	// Indicates whether the payment succeeded or failed
	Success bool `protobuf:"varint,1,opt,name=success" json:"success,omitempty"`
	// Response message from the payment bot. You should display this to the
	// user.
	Response string `protobuf:"bytes,2,opt,name=response" json:"response,omitempty"`
	// TODO Is it correct to use the whole hash?
	// This is the hash of the payment message that the payment bot received.
	// The client uses it to remove the correct pending transaction from the
	// list of pending transactions.
	ID string `protobuf:"bytes,3,opt,name=ID" json:"ID,omitempty"`
}

func (m *PaymentResponse) Reset()                    { *m = PaymentResponse{} }
func (m *PaymentResponse) String() string            { return proto.CompactTextString(m) }
func (*PaymentResponse) ProtoMessage()               {}
func (*PaymentResponse) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *PaymentResponse) GetSuccess() bool {
	if m != nil {
		return m.Success
	}
	return false
}

func (m *PaymentResponse) GetResponse() string {
	if m != nil {
		return m.Response
	}
	return ""
}

func (m *PaymentResponse) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

// Is Type.PAYMENT_INVOICE
type PaymentInvoice struct {
	// Timestamp (Unix time in seconds)
	// Not currently used but could be useful for the user to verify the
	// correctness of an invoice.
	Time int64 `protobuf:"varint,1,opt,name=time" json:"time,omitempty"`
	// This is a single compound coin that the invoicer wants to be funded. The
	// payer should send a message to the payment bot to fund this compound, if
	// they wish to pay the payee.
	CreatedCoin []byte `protobuf:"bytes,2,opt,name=createdCoin,proto3" json:"createdCoin,omitempty"`
	// The payee should fill this out to describe what the payment is for or
	// about.
	Memo string `protobuf:"bytes,3,opt,name=memo" json:"memo,omitempty"`
}

func (m *PaymentInvoice) Reset()                    { *m = PaymentInvoice{} }
func (m *PaymentInvoice) String() string            { return proto.CompactTextString(m) }
func (*PaymentInvoice) ProtoMessage()               {}
func (*PaymentInvoice) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *PaymentInvoice) GetTime() int64 {
	if m != nil {
		return m.Time
	}
	return 0
}

func (m *PaymentInvoice) GetCreatedCoin() []byte {
	if m != nil {
		return m.CreatedCoin
	}
	return nil
}

func (m *PaymentInvoice) GetMemo() string {
	if m != nil {
		return m.Memo
	}
	return ""
}

func init() {
	proto.RegisterType((*TextMessage)(nil), "parse.TextMessage")
	proto.RegisterType((*ChannelMessage)(nil), "parse.ChannelMessage")
	proto.RegisterType((*PaymentResponse)(nil), "parse.PaymentResponse")
	proto.RegisterType((*PaymentInvoice)(nil), "parse.PaymentInvoice")
	proto.RegisterEnum("parse.Type", Type_name, Type_value)
}

func init() { proto.RegisterFile("types.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 441 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x5c, 0x92, 0xdf, 0x8e, 0xd2, 0x40,
	0x14, 0xc6, 0x2d, 0xcb, 0xca, 0x72, 0x8a, 0x65, 0xf6, 0x2c, 0x2b, 0xd5, 0x78, 0xd1, 0x70, 0x45,
	0xbc, 0xf0, 0xc6, 0x27, 0xe8, 0x96, 0x11, 0x26, 0x4a, 0xa9, 0xd3, 0x41, 0x65, 0x6f, 0x9a, 0x5a,
	0x27, 0x4a, 0xdc, 0xfe, 0x49, 0xa7, 0x1a, 0x79, 0x23, 0x9f, 0xc9, 0xa7, 0x31, 0x2d, 0x0c, 0x6d,
	0xf6, 0xee, 0x7c, 0xdf, 0xf7, 0xeb, 0xd7, 0x39, 0xc9, 0x01, 0xb3, 0x3a, 0x14, 0x52, 0xbd, 0x29,
	0xca, 0xbc, 0xca, 0xf1, 0xb2, 0x88, 0x4b, 0x25, 0x67, 0x1f, 0xc1, 0x14, 0xf2, 0x4f, 0xb5, 0x96,
	0x4a, 0xc5, 0xdf, 0x25, 0x4e, 0xe0, 0x32, 0xc9, 0x1f, 0xf2, 0xd2, 0xee, 0x39, 0xc6, 0xfc, 0x9a,
	0x1f, 0x05, 0xda, 0x30, 0x48, 0x8f, 0x80, 0x7d, 0xe1, 0x18, 0xf3, 0x21, 0xd7, 0x12, 0x11, 0xfa,
	0xd5, 0x3e, 0x95, 0x76, 0xdf, 0x31, 0xe6, 0x17, 0xbc, 0x99, 0x67, 0x2b, 0xb0, 0xbc, 0x1f, 0x71,
	0x96, 0xc9, 0x07, 0xdd, 0xfa, 0x0a, 0x86, 0xaa, 0x90, 0xf1, 0x4f, 0x59, 0xb2, 0x45, 0xd3, 0x30,
	0xe2, 0xad, 0xd1, 0x6d, 0xef, 0x37, 0x99, 0x96, 0xb3, 0xcf, 0x30, 0x0e, 0xe2, 0x43, 0x2a, 0xb3,
	0x8a, 0x4b, 0x55, 0xe4, 0x99, 0x92, 0x35, 0xac, 0x7e, 0x25, 0x89, 0x54, 0xca, 0x36, 0x1c, 0x63,
	0x7e, 0xc5, 0xb5, 0xc4, 0x97, 0x70, 0x55, 0x9e, 0xa8, 0xe6, 0xf5, 0x43, 0x7e, 0xd6, 0x68, 0x41,
	0xef, 0xf4, 0xe7, 0x21, 0xef, 0xb1, 0xc5, 0xec, 0x1e, 0xac, 0x53, 0x31, 0xcb, 0x7e, 0xe7, 0xfb,
	0xa4, 0x5d, 0xc4, 0x68, 0x17, 0x41, 0x07, 0xcc, 0xa4, 0x94, 0x71, 0x25, 0xbf, 0x79, 0xf9, 0x3e,
	0x6b, 0x4a, 0x47, 0xbc, 0x6b, 0xd5, 0x5f, 0xa5, 0x32, 0xcd, 0x4f, 0xcd, 0xcd, 0xfc, 0xfa, 0x5f,
	0x0f, 0xfa, 0xe2, 0x50, 0x48, 0x34, 0x61, 0xe0, 0x6f, 0x22, 0xb1, 0x0b, 0x28, 0x79, 0x82, 0x04,
	0x46, 0x82, 0x7e, 0x11, 0xd1, 0x9a, 0x86, 0xa1, 0xbb, 0xa4, 0xc4, 0xc0, 0x1b, 0x18, 0x7b, 0x2b,
	0xd7, 0xf7, 0xe9, 0x87, 0xb3, 0xd9, 0xab, 0xb1, 0xed, 0xe2, 0x2e, 0x0a, 0xb6, 0xe1, 0x2a, 0x7a,
	0x4f, 0x77, 0x04, 0xf0, 0x05, 0xdc, 0x76, 0x9d, 0x88, 0xd3, 0x30, 0xd8, 0xf8, 0x21, 0x25, 0x26,
	0x8e, 0xc1, 0xac, 0xa3, 0x25, 0x15, 0x0d, 0x3b, 0x42, 0x1b, 0x26, 0x1d, 0xa3, 0x45, 0x9f, 0xe9,
	0x5e, 0x4e, 0x97, 0x2c, 0x14, 0x94, 0x13, 0x4b, 0xf7, 0x6a, 0xa7, 0x85, 0xc7, 0x68, 0x01, 0xd4,
	0x51, 0x48, 0x5d, 0xee, 0xad, 0x08, 0xc1, 0x29, 0xdc, 0xb4, 0xba, 0x05, 0xaf, 0xeb, 0x20, 0x70,
	0x77, 0x6b, 0xea, 0x8b, 0x48, 0x70, 0xd7, 0x0f, 0x5d, 0x4f, 0xb0, 0x8d, 0x4f, 0x26, 0x38, 0x01,
	0xa2, 0x83, 0x33, 0x7e, 0x5b, 0x6f, 0xac, 0x5d, 0xe6, 0x7f, 0xda, 0x30, 0x8f, 0x92, 0xe7, 0x5d,
	0x93, 0x53, 0x8f, 0xb2, 0x40, 0x90, 0x29, 0x4e, 0x01, 0x1f, 0x91, 0xd1, 0x96, 0x91, 0xbf, 0xef,
	0xee, 0x06, 0xf7, 0xc7, 0xbb, 0xfd, 0xfa, 0xb4, 0xb9, 0xe2, 0xb7, 0xff, 0x03, 0x00, 0x00, 0xff,
	0xff, 0x2d, 0x76, 0x34, 0xa4, 0xd4, 0x02, 0x00, 0x00,
}
