// Code generated by protoc-gen-go. DO NOT EDIT.
// source: fileTransfer/ftMessages.proto

package fileTransfer

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type NewFileTransfer struct {
	FileName             string   `protobuf:"bytes,1,opt,name=fileName,proto3" json:"fileName,omitempty"`
	TransferKey          []byte   `protobuf:"bytes,2,opt,name=transferKey,proto3" json:"transferKey,omitempty"`
	TransferMac          []byte   `protobuf:"bytes,3,opt,name=transferMac,proto3" json:"transferMac,omitempty"`
	NumParts             uint32   `protobuf:"varint,4,opt,name=numParts,proto3" json:"numParts,omitempty"`
	Size                 uint32   `protobuf:"varint,5,opt,name=size,proto3" json:"size,omitempty"`
	Retry                float32  `protobuf:"fixed32,6,opt,name=retry,proto3" json:"retry,omitempty"`
	Preview              []byte   `protobuf:"bytes,7,opt,name=preview,proto3" json:"preview,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NewFileTransfer) Reset()         { *m = NewFileTransfer{} }
func (m *NewFileTransfer) String() string { return proto.CompactTextString(m) }
func (*NewFileTransfer) ProtoMessage()    {}
func (*NewFileTransfer) Descriptor() ([]byte, []int) {
	return fileDescriptor_9d574f363dd34365, []int{0}
}

func (m *NewFileTransfer) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NewFileTransfer.Unmarshal(m, b)
}
func (m *NewFileTransfer) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NewFileTransfer.Marshal(b, m, deterministic)
}
func (m *NewFileTransfer) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NewFileTransfer.Merge(m, src)
}
func (m *NewFileTransfer) XXX_Size() int {
	return xxx_messageInfo_NewFileTransfer.Size(m)
}
func (m *NewFileTransfer) XXX_DiscardUnknown() {
	xxx_messageInfo_NewFileTransfer.DiscardUnknown(m)
}

var xxx_messageInfo_NewFileTransfer proto.InternalMessageInfo

func (m *NewFileTransfer) GetFileName() string {
	if m != nil {
		return m.FileName
	}
	return ""
}

func (m *NewFileTransfer) GetTransferKey() []byte {
	if m != nil {
		return m.TransferKey
	}
	return nil
}

func (m *NewFileTransfer) GetTransferMac() []byte {
	if m != nil {
		return m.TransferMac
	}
	return nil
}

func (m *NewFileTransfer) GetNumParts() uint32 {
	if m != nil {
		return m.NumParts
	}
	return 0
}

func (m *NewFileTransfer) GetSize() uint32 {
	if m != nil {
		return m.Size
	}
	return 0
}

func (m *NewFileTransfer) GetRetry() float32 {
	if m != nil {
		return m.Retry
	}
	return 0
}

func (m *NewFileTransfer) GetPreview() []byte {
	if m != nil {
		return m.Preview
	}
	return nil
}

func init() {
	proto.RegisterType((*NewFileTransfer)(nil), "parse.NewFileTransfer")
}

func init() { proto.RegisterFile("fileTransfer/ftMessages.proto", fileDescriptor_9d574f363dd34365) }

var fileDescriptor_9d574f363dd34365 = []byte{
	// 202 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x92, 0x4d, 0xcb, 0xcc, 0x49,
	0x0d, 0x29, 0x4a, 0xcc, 0x2b, 0x4e, 0x4b, 0x2d, 0xd2, 0x4f, 0x2b, 0xf1, 0x4d, 0x2d, 0x2e, 0x4e,
	0x4c, 0x4f, 0x2d, 0xd6, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x2d, 0x48, 0x2c, 0x2a, 0x4e,
	0x55, 0xba, 0xc8, 0xc8, 0xc5, 0xef, 0x97, 0x5a, 0xee, 0x86, 0xa4, 0x56, 0x48, 0x8a, 0x8b, 0x03,
	0xa4, 0xd7, 0x2f, 0x31, 0x37, 0x55, 0x82, 0x51, 0x81, 0x51, 0x83, 0x33, 0x08, 0xce, 0x17, 0x52,
	0xe0, 0xe2, 0x2e, 0x81, 0xaa, 0xf3, 0x4e, 0xad, 0x94, 0x60, 0x52, 0x60, 0xd4, 0xe0, 0x09, 0x42,
	0x16, 0x42, 0x56, 0xe1, 0x9b, 0x98, 0x2c, 0xc1, 0x8c, 0xaa, 0xc2, 0x37, 0x31, 0x19, 0x64, 0x7e,
	0x5e, 0x69, 0x6e, 0x40, 0x62, 0x51, 0x49, 0xb1, 0x04, 0x8b, 0x02, 0xa3, 0x06, 0x6f, 0x10, 0x9c,
	0x2f, 0x24, 0xc4, 0xc5, 0x52, 0x9c, 0x59, 0x95, 0x2a, 0xc1, 0x0a, 0x16, 0x07, 0xb3, 0x85, 0x44,
	0xb8, 0x58, 0x8b, 0x52, 0x4b, 0x8a, 0x2a, 0x25, 0xd8, 0x14, 0x18, 0x35, 0x98, 0x82, 0x20, 0x1c,
	0x21, 0x09, 0x2e, 0xf6, 0x82, 0xa2, 0xd4, 0xb2, 0xcc, 0xd4, 0x72, 0x09, 0x76, 0xb0, 0x1d, 0x30,
	0xae, 0x13, 0x5f, 0x14, 0x0f, 0xb2, 0xdf, 0x93, 0xd8, 0xc0, 0x3e, 0x36, 0x06, 0x04, 0x00, 0x00,
	0xff, 0xff, 0x3e, 0x0f, 0x1c, 0x27, 0x12, 0x01, 0x00, 0x00,
}
