// Code generated by go generate; DO NOT EDIT.
// This file was generated by robots at
// 2020-05-12 21:02:57.275479486 +0000 UTC m=+0.003920070
package cmd

const GITVERSION = `daeebfe disable stdout on the global jww logger`
const SEMVER = "1.3.0"
const DEPENDENCIES = `module gitlab.com/elixxir/client

go 1.13

require (
	github.com/golang-collections/collections v0.0.0-20130729185459-604e922904d3
	github.com/golang/protobuf v1.4.0
	github.com/gopherjs/gopherjs v0.0.0-20200217142428-fce0ec30dd00 // indirect
	github.com/pelletier/go-toml v1.6.0 // indirect
	github.com/pkg/errors v0.9.1
	github.com/smartystreets/assertions v1.0.1 // indirect
	github.com/spf13/afero v1.2.2 // indirect
	github.com/spf13/cast v1.3.1 // indirect
	github.com/spf13/cobra v1.0.0
	github.com/spf13/jwalterweatherman v1.1.0
	github.com/spf13/pflag v1.0.5 // indirect
	github.com/spf13/viper v1.6.2
	gitlab.com/elixxir/comms v0.0.0-20200415204952-6d63dd94a0ea
	gitlab.com/elixxir/crypto v0.0.0-20200410231849-90e859940f5d
	gitlab.com/elixxir/primitives v0.0.0-20200410231944-a57d71d577c9
	golang.org/x/crypto v0.0.0-20200323165209-0ec3e9974c59
	gopkg.in/ini.v1 v1.52.0 // indirect
)
`
