////////////////////////////////////////////////////////////////////////////////
// Copyright © 2020 Privategrity Corporation                                   /
//                                                                             /
// All rights reserved.                                                        /
////////////////////////////////////////////////////////////////////////////////

// Code generated by go generate; DO NOT EDIT.
// This file was generated by robots at
// 2020-02-06 14:09:54.442503 -0800 PST m=+0.007064579
package globals

const GITVERSION = `368d13e Merge branch 'XX-1807/Version-Tagging' into 'release'`
const SEMVER = "1.1.1"
const GLIDEDEPS = ``
