// Code generated by go generate; DO NOT EDIT.
// This file was generated by robots at
// 2020-01-27 13:49:48.509689574 -0800 PST m=+0.001619079
package globals

const GITVERSION = `6a0d897 Merge branch 'jonow-release-patch-69687' into 'release'`
const SEMVER = "0.2.0"
const GLIDEDEPS = ``
