// Code generated by go generate; DO NOT EDIT.
// This file was generated by robots at
// 2020-02-06 15:07:00.1145694 -0800 STD m=+0.048066801
package globals

const GITVERSION = `e77ca12 Merge branch 'authClient' into 'release'`
const SEMVER = "1.1.1"
const GLIDEDEPS = ``
