////////////////////////////////////////////////////////////////////////////////
// Copyright © 2022 xx foundation                                             //
//                                                                            //
// Use of this source code is governed by a license that can be found in the  //
// LICENSE file.                                                              //
////////////////////////////////////////////////////////////////////////////////

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.27.1
// 	protoc        v3.15.6
// source: ftMessages.proto

package broadcastFileTransfer

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// TransferInfoMsg is is transmitted to other users so that they can download a
// file transfer.
type TransferInfoMsg struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RecipientID []byte  `protobuf:"bytes,1,opt,name=recipientID,proto3" json:"recipientID,omitempty"` // ID to listen on to receive file
	FileName    string  `protobuf:"bytes,2,opt,name=fileName,proto3" json:"fileName,omitempty"`       // Name of the file
	FileType    string  `protobuf:"bytes,3,opt,name=fileType,proto3" json:"fileType,omitempty"`       // String that indicates type of file
	TransferKey []byte  `protobuf:"bytes,4,opt,name=transferKey,proto3" json:"transferKey,omitempty"` // 256-bit encryption key
	TransferMac []byte  `protobuf:"bytes,5,opt,name=transferMac,proto3" json:"transferMac,omitempty"` // 256-bit MAC of the entire file
	NumParts    uint32  `protobuf:"varint,6,opt,name=numParts,proto3" json:"numParts,omitempty"`      // Number of file parts
	Size        uint32  `protobuf:"varint,7,opt,name=size,proto3" json:"size,omitempty"`              // The size of the file, in bytes
	Retry       float32 `protobuf:"fixed32,8,opt,name=retry,proto3" json:"retry,omitempty"`           // Determines number of resends
	Preview     []byte  `protobuf:"bytes,9,opt,name=preview,proto3" json:"preview,omitempty"`         // A preview of the file
}

func (x *TransferInfoMsg) Reset() {
	*x = TransferInfoMsg{}
	if protoimpl.UnsafeEnabled {
		mi := &file_ftMessages_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TransferInfoMsg) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TransferInfoMsg) ProtoMessage() {}

func (x *TransferInfoMsg) ProtoReflect() protoreflect.Message {
	mi := &file_ftMessages_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TransferInfoMsg.ProtoReflect.Descriptor instead.
func (*TransferInfoMsg) Descriptor() ([]byte, []int) {
	return file_ftMessages_proto_rawDescGZIP(), []int{0}
}

func (x *TransferInfoMsg) GetRecipientID() []byte {
	if x != nil {
		return x.RecipientID
	}
	return nil
}

func (x *TransferInfoMsg) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

func (x *TransferInfoMsg) GetFileType() string {
	if x != nil {
		return x.FileType
	}
	return ""
}

func (x *TransferInfoMsg) GetTransferKey() []byte {
	if x != nil {
		return x.TransferKey
	}
	return nil
}

func (x *TransferInfoMsg) GetTransferMac() []byte {
	if x != nil {
		return x.TransferMac
	}
	return nil
}

func (x *TransferInfoMsg) GetNumParts() uint32 {
	if x != nil {
		return x.NumParts
	}
	return 0
}

func (x *TransferInfoMsg) GetSize() uint32 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *TransferInfoMsg) GetRetry() float32 {
	if x != nil {
		return x.Retry
	}
	return 0
}

func (x *TransferInfoMsg) GetPreview() []byte {
	if x != nil {
		return x.Preview
	}
	return nil
}

var File_ftMessages_proto protoreflect.FileDescriptor

var file_ftMessages_proto_rawDesc = []byte{
	0x0a, 0x10, 0x66, 0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x73, 0x2e, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x12, 0x15, 0x62, 0x72, 0x6f, 0x61, 0x64, 0x63, 0x61, 0x73, 0x74, 0x46, 0x69, 0x6c,
	0x65, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x65, 0x72, 0x22, 0x8f, 0x02, 0x0a, 0x0f, 0x54, 0x72,
	0x61, 0x6e, 0x73, 0x66, 0x65, 0x72, 0x49, 0x6e, 0x66, 0x6f, 0x4d, 0x73, 0x67, 0x12, 0x20, 0x0a,
	0x0b, 0x72, 0x65, 0x63, 0x69, 0x70, 0x69, 0x65, 0x6e, 0x74, 0x49, 0x44, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x0c, 0x52, 0x0b, 0x72, 0x65, 0x63, 0x69, 0x70, 0x69, 0x65, 0x6e, 0x74, 0x49, 0x44, 0x12,
	0x1a, 0x0a, 0x08, 0x66, 0x69, 0x6c, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x66, 0x69, 0x6c, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x66,
	0x69, 0x6c, 0x65, 0x54, 0x79, 0x70, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x66,
	0x69, 0x6c, 0x65, 0x54, 0x79, 0x70, 0x65, 0x12, 0x20, 0x0a, 0x0b, 0x74, 0x72, 0x61, 0x6e, 0x73,
	0x66, 0x65, 0x72, 0x4b, 0x65, 0x79, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0b, 0x74, 0x72,
	0x61, 0x6e, 0x73, 0x66, 0x65, 0x72, 0x4b, 0x65, 0x79, 0x12, 0x20, 0x0a, 0x0b, 0x74, 0x72, 0x61,
	0x6e, 0x73, 0x66, 0x65, 0x72, 0x4d, 0x61, 0x63, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0c, 0x52, 0x0b,
	0x74, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x65, 0x72, 0x4d, 0x61, 0x63, 0x12, 0x1a, 0x0a, 0x08, 0x6e,
	0x75, 0x6d, 0x50, 0x61, 0x72, 0x74, 0x73, 0x18, 0x06, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x08, 0x6e,
	0x75, 0x6d, 0x50, 0x61, 0x72, 0x74, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x18,
	0x07, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x04, 0x73, 0x69, 0x7a, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x72,
	0x65, 0x74, 0x72, 0x79, 0x18, 0x08, 0x20, 0x01, 0x28, 0x02, 0x52, 0x05, 0x72, 0x65, 0x74, 0x72,
	0x79, 0x12, 0x18, 0x0a, 0x07, 0x70, 0x72, 0x65, 0x76, 0x69, 0x65, 0x77, 0x18, 0x09, 0x20, 0x01,
	0x28, 0x0c, 0x52, 0x07, 0x70, 0x72, 0x65, 0x76, 0x69, 0x65, 0x77, 0x42, 0x31, 0x5a, 0x2f, 0x67,
	0x69, 0x74, 0x6c, 0x61, 0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x65, 0x6c, 0x69, 0x78, 0x78, 0x69,
	0x72, 0x2f, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x2f, 0x62, 0x72, 0x6f, 0x61, 0x64, 0x63, 0x61,
	0x73, 0x74, 0x46, 0x69, 0x6c, 0x65, 0x54, 0x72, 0x61, 0x6e, 0x73, 0x66, 0x65, 0x72, 0x62, 0x06,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_ftMessages_proto_rawDescOnce sync.Once
	file_ftMessages_proto_rawDescData = file_ftMessages_proto_rawDesc
)

func file_ftMessages_proto_rawDescGZIP() []byte {
	file_ftMessages_proto_rawDescOnce.Do(func() {
		file_ftMessages_proto_rawDescData = protoimpl.X.CompressGZIP(file_ftMessages_proto_rawDescData)
	})
	return file_ftMessages_proto_rawDescData
}

var file_ftMessages_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_ftMessages_proto_goTypes = []interface{}{
	(*TransferInfoMsg)(nil), // 0: broadcastFileTransfer.TransferInfoMsg
}
var file_ftMessages_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_ftMessages_proto_init() }
func file_ftMessages_proto_init() {
	if File_ftMessages_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_ftMessages_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TransferInfoMsg); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_ftMessages_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_ftMessages_proto_goTypes,
		DependencyIndexes: file_ftMessages_proto_depIdxs,
		MessageInfos:      file_ftMessages_proto_msgTypes,
	}.Build()
	File_ftMessages_proto = out.File
	file_ftMessages_proto_rawDesc = nil
	file_ftMessages_proto_goTypes = nil
	file_ftMessages_proto_depIdxs = nil
}
