// Code generated by go generate; DO NOT EDIT.
// This file was generated by robots at
// 2018-04-26 21:55:17.4265437 +0000 UTC m=+0.001850439
package cmd

const GITVERSION = `RUN go generate cmd/version.go!`
const SEMVER = "0.0.0a"
const GLIDEDEPS = `You need to run go generate cmd/version.go!`
