// Code generated by go generate; DO NOT EDIT.
// This file was generated by robots at
// 2018-10-01 12:44:17.113869437 -0700 PDT m=+0.001869310
package cmd

const GITVERSION = `4c3db8d Use more robust method to create user ID from uint in client main`
const SEMVER = "0.0.0a"
const GLIDEDEPS = `hash: ff2dfe00c8979503fc6f6deab869c44285341ac2b4d9a4629bce103ddcc04231
updated: 2018-08-23T13:44:23.38559806-07:00
imports:
- name: github.com/fsnotify/fsnotify
  version: c2828203cd70a50dcccfb2761f8b1f8ceef9a8e9
- name: github.com/golang/protobuf
  version: b27b920f9e71b439b873b17bf99f56467623814a
  subpackages:
  - proto
  - protoc-gen-go/descriptor
  - ptypes
  - ptypes/any
  - ptypes/duration
  - ptypes/timestamp
- name: github.com/grpc-ecosystem/go-grpc-middleware
  version: e9c5d9645c437ab1b204cff969a2c0fb16cd4276
  subpackages:
  - retry
  - util/backoffutils
  - util/metautils
- name: github.com/hashicorp/hcl
  version: ef8a98b0bbce4a65b5aa4c368430a80ddc533168
  subpackages:
  - hcl/ast
  - hcl/parser
  - hcl/printer
  - hcl/scanner
  - hcl/strconv
  - hcl/token
  - json/parser
  - json/scanner
  - json/token
- name: github.com/inconshreveable/mousetrap
  version: 76626ae9c91c4f2a10f34cad8ce83ea42c93bb75
- name: github.com/magiconair/properties
  version: c2353362d570a7bfa228149c62842019201cfb71
- name: github.com/mitchellh/go-homedir
  version: 58046073cbffe2f25d425fe1331102f55cf719de
  repo: https://github.com/mitchellh/go-homedir.git
  vcs: git
- name: github.com/mitchellh/mapstructure
  version: f15292f7a699fcc1a38a80977f80a046874ba8ac
- name: github.com/pelletier/go-toml
  version: c2dbbc24a97911339e01bda0b8cabdbd8f13b602
- name: github.com/spf13/afero
  version: 787d034dfe70e44075ccc060d346146ef53270ad
  subpackages:
  - mem
- name: github.com/spf13/cast
  version: 8965335b8c7107321228e3e3702cab9832751bac
- name: github.com/spf13/cobra
  version: ef82de70bb3f60c65fb8eebacbb2d122ef517385
  subpackages:
  - cobra
- name: github.com/spf13/jwalterweatherman
  version: 14d3d4c518341bea657dd8a226f5121c0ff8c9f2
- name: github.com/spf13/pflag
  version: d929dcbb10863323c436af3cf76cb16a6dfc9b29
- name: github.com/spf13/viper
  version: 907c19d40d9a6c9bb55f040ff4ae45271a4754b9
- name: github.com/xeipuuv/gojsonpointer
  version: 4e3ac2762d5f479393488629ee9370b50873b3a6
- name: github.com/xeipuuv/gojsonreference
  version: bd5ef7bd5415a7ac448318e64f11a24cd21e594b
- name: github.com/xeipuuv/gojsonschema
  version: da425ebb7609ba06a0f395fc8a254d1c303364a0
  vcs: git
- name: gitlab.com/privategrity/comms
  version: d7bf0d622910777e45d724abd4c738d229867a60
  repo: git@gitlab.com:privategrity/comms
  vcs: git
  subpackages:
  - client
  - connect
  - gateway
  - mixmessages
- name: gitlab.com/privategrity/crypto
  version: d7f54503c8958a451b29a9523816f9f50e9c7e79
  repo: git@gitlab.com:privategrity/crypto
  vcs: git
  subpackages:
  - coin
  - csprng
  - cyclic
  - format
  - forward
  - hash
  - messaging
  - verification
- name: golang.org/x/crypto
  version: 614d502a4dac94afa3a6ce146bd1736da82514c6
  subpackages:
  - blake2b
  - pbkdf2
- name: golang.org/x/net
  version: 922f4815f713f213882e8ef45e0d315b164d705c
  subpackages:
  - context
  - http/httpguts
  - http2
  - http2/hpack
  - idna
  - internal/timeseries
  - trace
- name: golang.org/x/sys
  version: 11551d06cbcc94edc80a0facaccbda56473c19c1
  subpackages:
  - cpu
  - unix
- name: golang.org/x/text
  version: 6e3c4e7365ddcc329f090f96e4348398f6310088
  subpackages:
  - secure/bidirule
  - transform
  - unicode/bidi
  - unicode/norm
- name: google.golang.org/genproto
  version: c66870c02cf823ceb633bcd05be3c7cda29976f4
  subpackages:
  - googleapis/rpc/status
- name: google.golang.org/grpc
  version: e00d24941bcee35dd163f4377d5371349f14baaf
  subpackages:
  - balancer
  - balancer/base
  - balancer/roundrobin
  - codes
  - connectivity
  - credentials
  - encoding
  - encoding/proto
  - grpclog
  - internal
  - internal/backoff
  - internal/channelz
  - internal/envconfig
  - internal/grpcrand
  - internal/transport
  - keepalive
  - metadata
  - naming
  - peer
  - reflection
  - reflection/grpc_reflection_v1alpha
  - resolver
  - resolver/dns
  - resolver/passthrough
  - stats
  - status
  - tap
- name: gopkg.in/yaml.v2
  version: 5420a8b6744d3b0345ab293f6fcba19c978f1183
testImports: []
`
